---
- name: Install libicu-dev and ImageMagick
  apt:
   name:
    - libicu-dev
    - imagemagick
   state: present
  become: yes

- name: Source .bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash


- name: Install Decidim gem
  gem:
    name: decidim

