---
- hosts: 192.168.10.15
#  become: yes
  tasks:
  - include_tasks: rbenv_install.yml
  - include_tasks: postgresql.yml
  - include_tasks: nodejs_install.yml
  - include_tasks: decidim_install.yml
  - include_tasks: decidim_app.yml
