---

- name: Update APT package cache
  apt:
    update_cache: yes
  become: yes


- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - curl
    - git
    - libssl-dev
    - zlib1g-dev
  become: yes

- name: Clone rbenv repository
  git:
    repo: https://github.com/rbenv/rbenv.git
    dest: ~/.rbenv
  register: rbenv_clone

- name: Add rbenv to PATH in .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH="$HOME/.rbenv/bin:$PATH"'
  when: rbenv_clone.changed

- name: Initialize rbenv in .bashrc
  lineinfile:
    path: ~/.bashrc
    line: 'eval "$(rbenv init -)"'
  when: rbenv_clone.changed

- name: Source .bashrc
  shell: source ~/.bashrc
  args:
    executable: /bin/bash

- name: Clone ruby-build repository
  git:
    repo: https://github.com/rbenv/ruby-build.git
    dest: ~/.rbenv/plugins/ruby-build

- name: Install Ruby 3.0.2
  command: rbenv install 3.0.2

- name: Set global Ruby version to 3.0.2
  command: rbenv global 3.0.2
  
- name: Add Gem Path
  lineinfile:
    path: ~/.bashrc
    line: 'export GEM_PATH=/home/vagrant/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems'

